pipeline {
    agent any
    environment {
        GIT_REPO_URL = 'https://github.com/mohamedbstar413/terraform'
    }
    tools{
        terraform 'terraform'
    }
    stages {
        stage('pull code') {
            steps {
                git branch: 'main', url: "${GIT_REPO_URL}"
            }
        }

        stage('terraform init and destroy ') {
            steps {
                dir('projects/book-review-app/infra') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                          credentialsId: 'aws']]) {
                        sh '''
                    terraform init
                    terraform destroy --auto-approve
                '''
                          }
                }
            }
        }

        
        stage('run npm install') {
            steps {
                dir('projects/book-review-app/infra/application/frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('build the react code') {
            steps {
                dir('projects/book-review-app/infra/application/frontend') {
                    sh '''
                    npm run build
                    '''
                    stash includes: 'build/**', name: 'react-build'
                }
            }
        }

        /*stage('copy lb_dns.txt file into build directory') {
            steps {
                dir('projects/book-review-app/infra/application/frontend') {
                    sh 'cp lb_dns.txt build/lb_dns.txt'
                }
            }
        }*/

        stage('run terraform apply') {
            steps {
                dir('projects/book-review-app/infra/application/frontend'){
                    unstash 'react-build'
                }
                dir('projects/book-review-app/infra') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                          credentialsId: 'aws']]) {
                        sh '''
                            terraform apply --auto-approve
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed (success or failure). Cleaning workspace...'
            cleanWs()
        }

        success {
            echo '✅ Pipeline completed successfully!'
        }

        failure {
            echo '❌ Pipeline failed. Please check the logs above for details.'
        }
    }
}
